In [1]:
from pathlib import Path

from mhd_cae_koopman.data_processing.utils import print_timeseries_info
from mhd_cae_koopman.data_processing.utils import get_grid_dimensions
from mhd_cae_koopman.utils import load_object

In [ ]:
ha = 300
file_name = "du.dat"
data_dir = Path("../../../../../../data")

In [3]:
base_data_path = data_dir / f"re1000_ha{ha}/3d/"
duvw_file_path = base_data_path / file_name
pkl_file_name = Path(file_name).with_suffix('.pkl').name
pkl_store_file_path = base_data_path / "pkl" / pkl_file_name
output_path=pkl_store_file_path

loaded_data = load_object(output_path)
print_timeseries_info(loaded_data['timeseries'], loaded_data['labels'])
num_timesteps, nx, ny, nz, num_variables = loaded_data['timeseries'].shape

Object successfully loaded from /cephfs/users/skowronek/Documents/PhD/nuclear_fusion_cooling/data/re1000_ha300/3d/pkl/du.pkl

Timeseries Data Summary
Number of snapshots (time steps): 100
Grid dimensions (nx, ny, nz):   541 x 91 x 91
Number of points per snapshot:  4480021
Number of variables:              6

--- Variable Labels ---
['x', 'y', 'z', 'du_dx', 'du_dy', 'du_dz']

--- Data Preview (First 5 points of first snapshot) ---
  Point 1 : [ 0. -1. -1.  0.  0.  0.]
  Point 2 : [ 0.         -1.         -0.99458132  0.          0.          0.        ]
  Point 3 : [ 0.         -1.         -0.98722071  0.          0.          0.        ]
  Point 4 : [ 0.         -1.         -0.97793765  0.          0.          0.        ]
  Point 5 : [ 0.         -1.         -0.96676442  0.          0.          0.        ]


In [4]:
reshaped = loaded_data['timeseries'].reshape(num_timesteps, nx, ny, nz, 6, order='C')

In [5]:
reshaped[0, :5, 0, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.02327106, -1.        , -1.        ],
       [ 0.04654211, -1.        , -1.        ],
       [ 0.06981317, -1.        , -1.        ],
       [ 0.09308423, -1.        , -1.        ]])

In [6]:
reshaped[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -0.99458132, -1.        ],
       [ 0.        , -0.98722071, -1.        ],
       [ 0.        , -0.97793765, -1.        ],
       [ 0.        , -0.96676442, -1.        ]])

In [7]:
reshaped[0, 0, 0, :5, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -1.        , -0.99458132],
       [ 0.        , -1.        , -0.98722071],
       [ 0.        , -1.        , -0.97793765],
       [ 0.        , -1.        , -0.96676442]])

In [8]:
reshaped = loaded_data['timeseries'].reshape(num_timesteps, nx, ny, nz, num_variables, order='F')

In [9]:
reshaped[0, :5, 0, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.02327106, -1.        , -1.        ],
       [ 0.04654211, -1.        , -1.        ],
       [ 0.06981317, -1.        , -1.        ],
       [ 0.09308423, -1.        , -1.        ]])

In [10]:
reshaped[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -0.99458132, -1.        ],
       [ 0.        , -0.98722071, -1.        ],
       [ 0.        , -0.97793765, -1.        ],
       [ 0.        , -0.96676442, -1.        ]])

In [11]:
reshaped[0, 0, 0, :5, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -1.        , -0.99458132],
       [ 0.        , -1.        , -0.98722071],
       [ 0.        , -1.        , -0.97793765],
       [ 0.        , -1.        , -0.96676442]])

In [12]:
zyx = loaded_data['timeseries'].reshape((num_timesteps, nz, ny, nx, num_variables), order='C')

In [13]:
zyx[0, :5, 0, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.11635528,  0.96676442, -1.        ],
       [ 0.25598162,  0.88451809, -1.        ],
       [ 0.39560796,  0.76629394, -1.        ],
       [ 0.5352343 ,  0.62648942, -1.        ]])

In [14]:
zyx[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -0.95374575,  0.96676442],
       [ 0.        , -0.84081347,  0.88451809],
       [ 0.        , -0.68397958,  0.76629394],
       [ 0.        , -0.50972415,  0.62648942]])

In [15]:
zyx[0, 0, 0, :5, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -1.        , -0.99458132],
       [ 0.        , -1.        , -0.98722071],
       [ 0.        , -1.        , -0.97793765],
       [ 0.        , -1.        , -0.96676442]])

In [16]:
num_points = nz * ny * nx
zyx_C = loaded_data['timeseries'].reshape((num_timesteps, nz, ny, nx, num_variables), order='C')
xyz_view_on_zyx_C = zyx_C.transpose(0, 3, 2, 1, 4)
data_C_ordered = xyz_view_on_zyx_C.reshape((num_timesteps, num_points, num_variables), order='C')
xyz_C = data_C_ordered.reshape((num_timesteps, nx, ny, nz, num_variables))

In [17]:
xyz_C[0, :5, 0, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -1.        , -0.99458132],
       [ 0.        , -1.        , -0.98722071],
       [ 0.        , -1.        , -0.97793765],
       [ 0.        , -1.        , -0.96676442]])

In [18]:
xyz_C[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -0.95374575,  0.96676442],
       [ 0.        , -0.84081347,  0.88451809],
       [ 0.        , -0.68397958,  0.76629394],
       [ 0.        , -0.50972415,  0.62648942]])

In [19]:
xyz_C[0, 0, 0, :5, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.11635528,  0.96676442, -1.        ],
       [ 0.25598162,  0.88451809, -1.        ],
       [ 0.39560796,  0.76629394, -1.        ],
       [ 0.5352343 ,  0.62648942, -1.        ]])