In [2]:
from pathlib import Path

from mhd_cae_koopman.data_processing.utils import print_timeseries_info
from mhd_cae_koopman.data_processing.utils import get_grid_dimensions
from mhd_cae_koopman.utils import load_object

ha = 300
file_name = "du.dat"
data_dir = Path("../../../../../data")

base_data_path = data_dir / f"re1000_ha{ha}/3d/"
duvw_file_path = base_data_path / file_name
pkl_file_name = Path(file_name).with_suffix('.pkl').name
pkl_store_file_path = base_data_path / "pkl" / pkl_file_name
output_path=pkl_store_file_path

loaded_data = load_object(output_path)
print_timeseries_info(loaded_data['timeseries'], loaded_data['labels'])
nx, ny, nz = get_grid_dimensions(loaded_data['timeseries'])

Object successfully loaded from /cephfs/users/skowronek/Documents/PhD/nuclear_fusion_cooling/data/re1000_ha300/3d/pkl/du.pkl

Timeseries Data Summary
Number of snapshots (time steps): 100
Number of points per snapshot:    4480021
Number of variables:              6
Calculated grid dimensions:       541 x 91 x 91 (using indices (0, 1, 2))

--- Variable Labels ---
['x', 'y', 'z', 'du_dx', 'du_dy', 'du_dz']

--- Data Preview (First 5 points of first snapshot) ---
  Point 1 : [ 0. -1. -1.  0.  0.  0.]
  Point 2 : [ 0.02327106 -1.         -1.          0.          0.          0.        ]
  Point 3 : [ 0.04654211 -1.         -1.          0.          0.          0.        ]
  Point 4 : [ 0.06981317 -1.         -1.          0.          0.          0.        ]
  Point 5 : [ 0.09308423 -1.         -1.          0.          0.          0.        ]


In [3]:
reshaped = loaded_data['timeseries'].reshape(100, nx, ny, nz, 6, order='C')

In [4]:
reshaped[0, :5, 0, 0, :3]

array([[ 0.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.86299541e+00, -7.39551116e-01, -1.00000000e+00],
       [ 7.72599082e+00, -3.16666667e-01, -1.00000000e+00],
       [ 1.15889862e+01,  3.16118792e-17, -1.00000000e+00],
       [ 2.86233997e+00,  3.42602407e-01, -1.00000000e+00]])

In [5]:
reshaped[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 2.11766616, -1.        , -1.        ],
       [ 4.23533232, -1.        , -1.        ],
       [ 6.35299848, -1.        , -1.        ],
       [ 8.47066464, -1.        , -1.        ]])

In [6]:
reshaped[0, 0, 0, :5, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.02327106, -1.        , -1.        ],
       [ 0.04654211, -1.        , -1.        ],
       [ 0.06981317, -1.        , -1.        ],
       [ 0.09308423, -1.        , -1.        ]])

In [7]:
reshaped = loaded_data['timeseries'].reshape(100, nx, ny, nz, 6, order='F')

In [8]:
reshaped[0, :5, 0, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.02327106, -1.        , -1.        ],
       [ 0.04654211, -1.        , -1.        ],
       [ 0.06981317, -1.        , -1.        ],
       [ 0.09308423, -1.        , -1.        ]])

In [9]:
reshaped[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -0.99458132, -1.        ],
       [ 0.        , -0.98722071, -1.        ],
       [ 0.        , -0.97793765, -1.        ],
       [ 0.        , -0.96676442, -1.        ]])

In [10]:
reshaped[0, 0, 0, :5, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.        , -1.        , -0.99458132],
       [ 0.        , -1.        , -0.98722071],
       [ 0.        , -1.        , -0.97793765],
       [ 0.        , -1.        , -0.96676442]])

In [11]:
reshaped = loaded_data['timeseries'].reshape(100, nz, ny, nx, 6, order='F')

In [15]:
reshaped[0, :5, 0, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 0.02327106, -1.        , -1.        ],
       [ 0.04654211, -1.        , -1.        ],
       [ 0.06981317, -1.        , -1.        ],
       [ 0.09308423, -1.        , -1.        ]])

In [16]:
reshaped[0, 0, :5, 0, :3]

array([[ 0.        , -1.        , -1.        ],
       [ 2.11766616, -1.        , -1.        ],
       [ 4.23533232, -1.        , -1.        ],
       [ 6.35299848, -1.        , -1.        ],
       [ 8.47066464, -1.        , -1.        ]])

In [17]:
reshaped[0, 0, 0, :5, :3]

array([[ 0.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 3.86299541e+00, -7.39551116e-01, -1.00000000e+00],
       [ 7.72599082e+00, -3.16666667e-01, -1.00000000e+00],
       [ 1.15889862e+01,  3.16118792e-17, -1.00000000e+00],
       [ 2.86233997e+00,  3.42602407e-01, -1.00000000e+00]])